pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=main
      - "label=automerge"
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
